   @baseUrl = "http://localhost:3000/"
    # Login
    # @name tokenAPI
    POST {{baseUrl}}/Auth/login HTTP/1.1
    Content-Type: application/json
    
    {
        "email": "clecio.sb@gmail.com",
        "password": "202020"
    }
    ###
    
    @authToken = {{tokenAPI.response.body.token}}
    # Get User
    # @name getUser
    GET {{baseUrl}}/me
    Authorization: Bearer {{authToken}}