POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email": "clecio.sb@gmail.com",
    "name": "clecio barbosa",
    "password": "202020",
    "passwordConfirmation": "202020"
}